version: '3.8'

services:
  server:
    build: ./server
    image: face-reco-server:v1
    container_name: face-reco-server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: face-reco-client:v1
    container_name: face-reco-client
    ports:
      - "5173:80"
      - "443:443"
    depends_on:
      - server
